### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by vadym-scythia** [VolDonets/reinforcement_learining#1]
Considering to add `swig` for and  `pip install "gymnasium[atari,accept-rom-license]"`

For windows users swig might be install via [choco](https://chocolatey.org/) as follows:
open shell as administrator
`choco install swig`

and gemnasium atari in venv
`pip install "gymnasium[atari,accept-rom-license]"`

**Comment by vadym-scythia** [comment]
swig needed for box2d-py package

**Comment by vadym-scythia** [comment]
Added everything in this markdown file. Please, review 

[README.md](https://github.com/user-attachments/files/17299556/README.md)

**Comment by VolDonets** [comment]
> Considering to add `swig` for and `pip install "gymnasium[atari,accept-rom-license]"`
> 
> For windows users swig might be install via [choco](https://chocolatey.org/) as follows: open shell as administrator `choco install swig`
> 
> and gemnasium atari in venv `pip install "gymnasium[atari,accept-rom-license]"`

I'm not quite sure about adding "swig", it hadn't been installed while I configured environment.

**Comment by VolDonets** [comment]
> Added everything in this markdown file. Please, review
> 
> [README.md](https://github.com/user-attachments/files/17299556/README.md)

Many thanks for your "README.md" file, I've added it to the repo already.
